#!/usr/bin/python3

import sys
import os
from pathlib import Path

current_dir = Path(__file__).parent.resolve()
project_dir = current_dir.parent
modules_dir = current_dir.joinpath("python_modules")

#add modules dir
sys.path.insert(0,str(modules_dir))

from codecheck.walk import check_modify_source;
from codecheck.state import StateAndConfiguration

if __name__ == "__main__":
    """
    FIXME

    Note:
    `check_only` must be set to true for normal operation mode.
    """

    check_only = False
    state = StateAndConfiguration(project_dir, check_only)

    rv = check_modify_source(
            ["include", "examples"] #dirs to include
            ,[] #dirs and files to exclude (does not purge the dir)
            ,state
        )

    sys.exit(rv)
