#!/usr/bin/env python3
# Copyright - 2019 - Jan Christoph Uhde <Jan@UhdeJC.com>

import sys
import os
from pathlib import Path

import sys
if sys.version_info[0] < 3 or sys.version_info[1] < 7:
        raise Exception("Must be using Python 3.7")

project_dir = Path(os.getcwd())
python_dir = Path(__file__).parent.resolve()
modules_dir = python_dir.joinpath("python_modules")

#add modules dir
sys.path.insert(0,str(modules_dir))

from codecheck.walk import check_modify_source;
from codecheck.state import StateAndConfiguration

if __name__ == "__main__":
    """
    FIXME

    Note:
    `check_only` must be set to true for normal operation mode.
    """

    debug = False
    check_only = False
    state_and_conf = StateAndConfiguration(project_dir, check_only)

    if debug:
        conf = state_and_conf.configuration

        #conf.fix_include_guards = None
        #conf.fix_copyright = None
        #conf.fix_ifdef = None

        conf.create_operation_list()

    rv = check_modify_source(["include", "examples", "tests"] #dirs to include
                            ,[] #dirs and files to exclude (does not purge the dir)
                            ,state_and_conf
                            )

    sys.exit(rv)
