#!/usr/bin/env bash
set -u

support_dir="${project_root:-"$(realpath -s "$(dirname "$(readlink -s -f "${BASH_SOURCE[0]}")")")"}"
. "$support_dir/bash/find-clang-format"
find_clang_format

command=(
    "${support_dir}/helper_scripts/clang-format-diff"
    --verbose
    -i
    -binary "${clang_format_binary}"
    -style=file
    -p1
)

#echo "${command[@]}"
"${command[@]}" < <(git diff -U0 --no-color "$@")

