#!/bin/bash

branch_name=$(git symbolic-ref --short HEAD)

if [[ $branch_name != "github_master" ]]; then
    echo "not on github_master"
    exit 1
fi

git add -u && \
git commit --amend && \
git push -u --force github HEAD:master
