#!/bin/bash
# Copyright - 2015 - Jan Christoph Uhde <Jan@UhdeJC.com>


project_root="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
build_base="${project_root}-build"
build_type="release"
just_make=false
do_clean=false
do_test=false
asan=false
build_prefix="<> "


lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
fi

function main(){
section "prepare build"
msg "parse arguments"
args=()
cm_flags=()
while [[ -n "$1" ]]; do
  case "$1" in
    -j|--just-make)
      just_make=true
      shift
    ;;
    -v|--verbose)
      export VERBOSE=1
      export V=1
      shift
    ;;
    -d|--debug)
      build_type="debug"
      shift
    ;;
    -r|--release)
      build_type="release"
      shift
    ;;
    -t|--testing)
      cm_flags+=( '-DCMAKE_TESTING=ON' )
      do_test=true
      shift
    ;;
    -e|--examples)
      cm_flags+=( '-DLIBOBI_EXAMPLES=ON' )
      shift
    ;;
    -c|--clean)
      do_clean=true
      shift
    ;;
    --gcc)
      export CXX=g++
      export CC=gcc
      #cm_flags+=( '-DCMAKE_CXX_COMPILER=g++' )
      shift
    ;;
    --clang)
      export CXX=clang++
      export CC=clang
      #cm_flags+=( '-DCMAKE_CXX_COMPILER=clang++' )
      shift
    ;;
    --travis)
      travis=true
      shift
    ;;
    -cd|--change-directory)
      change_dir=true
      shift
    ;;
    -a|--asan)
      asan=true
      shift
    ;;
    *)
      args+=( "$1" )
      shift
    ;;
  esac
done

msg "set build type"
case $build_type in
  release)
    cm_flags+=( '-DCMAKE_BUILD_TYPE=Release' )
  ;;
  debug)
    cm_flags+=( '-DCMAKE_BUILD_TYPE=Debug' )
  ;;
  *)
    ferr "build type $build_type not supported!"
  ;;
esac
build_root="$build_base/$build_type"


msg "create build directories"
if $do_clean; then
  rm -fr $build_root || ferr "failed to clean build dir"
fi

test -d $build_root || mkdir -p $build_root || ferr "failed to create build dir"

msg "create symlinks"
rm -fr $build_base/current
ln -s $build_root $build_base/current

msg "change into build dir"
cd $build_root || ferr "failed to change into build dir"

if ! $just_make || ! [[ -f makefile && -f Makefile ]]; then
  section "running cmake"
  cmake "${cm_flags[@]}" "${args[@]}" "$project_root" || ferr "configuring with camke failed"
  echo
  if $do_test && ! ${IN_TRAVIS:-false}; then
    msg "enable testing"
    touch .do_test
  fi
fi

section "running make"
make -j $(nproc) || ferr "make failed"

echo
section "build done"
echo

if [[ -f .do_test ]]; then
  section "running tests"
  ctest -VV || fserr $?
  echo
  section "tests done"
  echo
fi


if ${change_dir:-false}; then
  msg "starting shell in build directory"
  echo
  exec bash
fi
}

main "$@"
