set(basic-warnings "-Wall -Wextra -Wpedantic")
set(more-warnings  "${basic-warnings} -Wcast-align -Wcast-qual -Wconversion")
set(stone-warnings "${more-warnings}  -Wctor-dtor-privacy")
set(stone-warnings "${stone-warnings} -Wdisabled-optimization -Wdouble-promotion")
set(stone-warnings "${stone-warnings} -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch")
set(stone-warnings "${stone-warnings} -Wlogical-op -Wmissing-include-dirs")
set(stone-warnings "${stone-warnings} -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls")
set(stone-warnings "${stone-warnings} -Wshadow -Wsign-conversion -Wsign-promo ")
set(stone-warnings "${stone-warnings} -Wstrict-null-sentinel -Wstrict-overflow=5")
set(stone-warnings "${stone-warnings} -Wtrampolines -Wunsafe-loop-optimizations")
set(stone-warnings "${stone-warnings} -Wvector-operation-performance")
set(stone-warnings "${stone-warnings} -Wzero-as-null-pointer-constant")
set(stone-warnings-extra "${stone-warnings} -Wundef -Wmissing-declarations")
