set(ext-basics-header
    "include/ext/config.hpp"
    "include/ext/std.hpp"

    "include/ext/algorithm/basic.hpp"
    "include/ext/algorithm/string_distances.hpp"

    "include/ext/macros/advanced.hpp"
    "include/ext/macros/compiler.hpp"
    "include/ext/macros/general.hpp"
    "include/ext/macros/platform.hpp"

    "include/ext/memory/align.hpp"
    "include/ext/memory/tagged_pointer.hpp"

    #"include/ext/meta/has_member.hpp"
    #"include/ext/meta/if.hpp"
    #"include/ext/meta/if_all_any.hpp"
    #"include/ext/meta/is_one_of.hpp"
    #"include/ext/meta/pack.hpp"
    #"include/ext/meta/static_lambda.hpp"
    #"include/ext/meta/tuple.hpp"
    #"include/ext/meta/void_t.hpp"

    "include/ext/structures/binary_index_tree.hpp"

    "include/ext/util/access_private.hpp"
    "include/ext/util/any_printable.hpp"
    "include/ext/util/basic.hpp"
    "include/ext/util/cast.hpp"
    "include/ext/util/container_helper.hpp"
    "include/ext/util/encode.hpp"
    "include/ext/util/endian.hpp"
    "include/ext/util/enum.hpp"
    "include/ext/util/except.hpp"
    "include/ext/util/files.hpp"
    "include/ext/util/function_cache.hpp"
    "include/ext/util/functional.hpp"
    "include/ext/util/io.hpp"
    "include/ext/util/load_library.hpp"
    "include/ext/util/result.hpp"
    "include/ext/util/scope_guard.hpp"
    "include/ext/util/scoped_timer.hpp"
    "include/ext/util/serialization.hpp"
    "include/ext/util/show.hpp"
    "include/ext/util/stat.hpp"
    "include/ext/util/string.hpp"
    "include/ext/util/to_str_eam.hpp"
    "include/ext/util/tracing_classes.hpp"
    "include/ext/util/type_to_string.hpp"
    "include/ext/util/windows_strings.hpp"
)
