set(libobi_header
    "include/obi/config.hpp"
    "include/obi/logging.hpp"
    "include/obi/std.hpp"

    "include/obi/algorithm/basic.hpp"
    "include/obi/algorithm/string_distances.hpp"

    "include/obi/concurrent/hierarchical_mutex.hpp"
    "include/obi/concurrent/threadsafe_queue.hpp"
    "include/obi/concurrent/threadsafe_stack.hpp"

    "include/obi/logging/definitions.hpp"
    "include/obi/logging/functionality.hpp"

    "include/obi/macros/advanced.hpp"
    "include/obi/macros/compiler.hpp"
    "include/obi/macros/general.hpp"
    "include/obi/macros/platform.hpp"

    "include/obi/math/basic_functions.hpp"
    "include/obi/math/geometry/simple_shapes.hpp"
    "include/obi/math/primes.hpp"

    "include/obi/memory/align.hpp"
    "include/obi/memory/tagged_pointer.hpp"

    "include/obi/meta/has_member.hpp"
    "include/obi/meta/if.hpp"
    "include/obi/meta/if_all_any.hpp"
    "include/obi/meta/is_one_of.hpp"
    "include/obi/meta/pack.hpp"
    "include/obi/meta/static_lambda.hpp"
    "include/obi/meta/tuple.hpp"
    "include/obi/meta/void_t.hpp"

    "include/obi/structures/binary_index_tree.hpp"
    "include/obi/structures/multi_array.hpp"
    "include/obi/structures/simple2darray.hpp"
    "include/obi/structures/vector.hpp"

    "include/obi/util/access_private.hpp"
    "include/obi/util/any_printable.hpp"
    "include/obi/util/basic.hpp"
    "include/obi/util/cast.hpp"
    "include/obi/util/container_helper.hpp"
    "include/obi/util/encode.hpp"
    "include/obi/util/endian.hpp"
    "include/obi/util/except.hpp"
    "include/obi/util/files.hpp"
    "include/obi/util/function_cache.hpp"
    "include/obi/util/functional.hpp"
    "include/obi/util/io.hpp"
    "include/obi/util/load_library.hpp"
    "include/obi/util/result.hpp"
    "include/obi/util/scope_guard.hpp"
    "include/obi/util/scoped_timer.hpp"
    "include/obi/util/serialization.hpp"
    "include/obi/util/show.hpp"
    "include/obi/util/stat.hpp"
    "include/obi/util/string.hpp"
    "include/obi/util/to_str_eam.hpp"
    "include/obi/util/tracing_classes.hpp"
    "include/obi/util/type_to_string.hpp"
    "include/obi/util/windows_strings.hpp"
)
