#!/bin/bash

project_root=${project_root:-..}
lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "running make"
cd $build_root || ferr "failed to change into build dir"
#command
make -j $(nproc) || ferr "running make - failed" $?
#end
echo
