#!/bin/bash

lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "install external libs"
cd "$project_root" || exit 1
#command
if [[ -e ./external_libs/init_libs  ]]; then
    cd external_libs && ./init_libs || exit 1
#else if [[ -e ./external_libs/init_libs.py  ]]; then
#    echo "geil!"
else
    echo "no external libs specified"
fi
#end
echo
