#!/bin/bash

lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "system info"
#command
echo "sources list ##################"
cat /etc/apt/sources.list
echo "cpu info ######################"
cat /proc/cpuinfo
echo "mem info ######################"
cat /proc/meminfo
echo "###############################"
#end
echo
