#!/bin/bash

project_root=${project_root:-..}
lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

if ! $do_test; then
    exit 0
fi

#prepare
section "running tests"
cd $build_base/current || ferr "unable to change into current build dir"
#command
ctest -VV || fserr "running tests - failed" $?
#end
echo
