#!/bin/bash

project_root=${project_root:-..}
lib=$project_root/.build_scripts/build_lib
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "variable info"
#command
echo "project_root: $project_root"
echo "build_base:   $build_base"
echo "build_root:   $build_root"
echo
echo "build_type:   $build_type"
echo "examples:     $examples"
echo "tests:        $tests"
echo
echo "PATH:         $PATH"
echo "CXX:          $CXX"
echo "CC:           $CC "
echo "CXXFLAGS:     $CXXFLAGS"
echo "CFLAGS:       $CFLAGS"
echo "RPATH         $RPATH"
echo "COMPILER:     $COMPILER"
echo "IN_TRAVIS:    $IN_TRAVIS"
#end
echo
