#!/bin/bash
if $SANITIZER; then

    ## try to get rid of locales that slow down travis
    cat /etc/locale.gen | grep '^#' > /etc/locale.gen.new
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen.new
    mv /etc/locale.gen.new /etc/locale.gen

    dpkg-divert --divert /usr/share/i18n/SUPPORTED.dpkg --rename /usr/share/i18n/SUPPORTED
    echo 'en_US.UTF-8 UTF-8' > /usr/share/i18n/SUPPORTED


    # install gcc from disco - the linker will have '--push-state--no-as-needed'
    echo "deb http://de.archive.ubuntu.com/ubuntu disco main restricted universe multiverse" \
        >> /etc/apt/sources.list

    apt-get update
    apt-get install binutils $CXX
fi
