#!/bin/bash

if $SANITIZER; then

    ## does not work because PPA is gone / does not contain binutils
    ## sudo add-apt-repository ppa:jonathonf/binutils-2.30-2 --yes || exit 1
    ## sudo apt-get update -qq --yes || exit 1
    ## sudo apt-get install apt-show-versions
    ## apt-show-versions -a binutils
    ## sudo apt-get install -qq --yes --force-yes

    echo "en_US.UTF-8 UTF-8" \
        | sudo tee /etc/locale.gen
    echo "deb http://de.archive.ubuntu.com/ubuntu disco main restricted universe multiverse" \
        | sudo tee -a /etc/apt/sources.list

    sudo apt-get update
    sudo apt-get install binutils $CXX
fi
