#!/bin/bash

if $SANITIZER; then
    #sudo add-apt-repository ppa:jonathonf/binutils-2.30-2 --yes || exit 1
    #sudo apt-get update -qq --yes || exit 1
    #sudo apt-get install apt-show-versions
    #apt-show-versions -a binutils
    #sudo apt-get install -qq --yes --force-yes

    sudo apt-get install texinfo
    git clone git://sourceware.org/git/binutils-gdb.git binutils
    cd binutils
    git checkout binutils-2_30
    ./configure
    make &> build_log || cat build_log
    sudo make install
fi
