if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(obi_basic-warnings       "-Wall -Wextra -Wpedantic")
    set(obi_more-warnings        "${obi_basic-warnings} -Wcast-align -Wcast-qual -Wconversion")
    set(obi_stone-warnings       "${obi_more-warnings}  -Wctor-dtor-privacy")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wdisabled-optimization -Wdouble-promotion")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wlogical-op -Wmissing-include-dirs")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wshadow -Wsign-conversion -Wsign-promo ")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wstrict-null-sentinel -Wstrict-overflow=5")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wtrampolines -Wunsafe-loop-optimizations")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wvector-operation-performance")
    set(obi_stone-warnings       "${obi_stone-warnings} -Wzero-as-null-pointer-constant")
    set(obi_stone-warnings-extra "${obi_stone-warnings} -Wundef -Wmissing-declarations")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(obi_basic-warnings       "-Wall -Wextra -Wpedantic")
    set(obi_more-warnings        "${obi_basic-warnings} -Wcast-align -Wcast-qual -Wconversion")
    set(obi_stone-warnings       "${obi_more-warnings} ")
    set(obi_stone-warnings-extra "${obi_stone-warnings} ")
else()
    message(STATUS "Flags for your compiler(${CMAKE_COMPILER_IS}) are not defined. Please update compiler-warnings.cmake")
    set(obi_basic-warnings       "")
    set(obi_more-warnings        "${obi_basic-warnings}")
    set(obi_stone-warnings       "${obi_more-warnings}")
    set(obi_stone-warnings-extra "${obi_stone-warnings}")
endif()
